# https://gohugo.io/getting-started/configuration/#all-configuration-settings
baseURL: 'https://nerves-project.org/'
languageCode: 'en-us'
title: 'Nerves Project'
Copyright: 'The Nerves Project Authors'

# https://gohugo.io/variables/site/#the-siteparams-variable
params:
  description: >
    Nerves is the open-source platform and infrastructure you need to build,
    deploy, and securely manage your fleet of IoT devices at speed and scale.
  dateFormat: "January 2, 2006"

# https://gohugo.io/content-management/menus
menu:
  main:
    - name: Learn
      url: /learn
      weight: 1
    - name: Code
      url: /code
      weight: 2
    - name: 'Community'
      url: '/community'
      weight: 3
    - name: 'Sponsors'
      url: '/sponsors'
      weight: 4
    - name: 'Videos'
      url: '/videos'
      weight: 5
    - name: 'Articles'
      url: '/articles'
      weight: 6
  footer1:
    - name: 'Docs'
      url: 'https://hexdocs.pm/nerves'
      weight: 1
    - name: 'Newsletter'
      url: '/newsletter'
      weight: 2
    - name: 'Tips'
      url: 'https://tips.nerves-project.org'
      weight: 3
    - name: 'Blog'
      url: 'https://embedded-elixir.com'
      weight: 4
    - name: 'Cases'
      url: '/cases'
      weight: 5
  footer2:
    - name: 'Forum'
      url: 'https://elixirforum.com/c/elixir-framework-forums/nerves-forum/74'
      pre: 'img/elixir-forum.svg'
      weight: 1
    - name: 'Github'
      url: 'https://github.com/nerves-project'
      pre: 'img/github.svg'
      weight: 2
    - name: 'Slack'
      url: 'https://elixir-slack.community/'
      pre: 'img/slack.svg'
    - name: 'Discord'
      url: 'https://discord.gg/elixir'
      pre: 'img/discord.svg'
      weight: 3
    - name: 'Bluesky'
      url: 'https://bsky.app/profile/nerves-project.org'
      pre: 'img/bsky.svg'
      weight: 4
    - name: 'Mastodon'
      url: 'https://fosstodon.org/@NervesProject'
      pre: 'img/mastodon.svg'
      weight: 4
    - name: 'Meetup'
      url: 'https://www.meetup.com/nerves'
      pre: 'img/meetup.svg'
      weight: 5

# https://gohugo.io/content-management/taxonomies/
taxonomies:
  tag: tags

# https://gohugo.io/news/0.60.0-relnotes/
markup:
  goldmark:
    renderer:
      unsafe: true
